- name: Remediate Vulnerabilities on Red Hat Enterprise Linux
  hosts: sl-ac4-solqa-ia-08.bmc.com
  tasks:
    - name: Print Remediated Vulnerabilities
      debug:
        msg: "Remediated Vulnerabilities Updated"